# -*- coding: utf-8 -*-
"""Market_researcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iab5ZjoJ-7BmQ3AoSyoFMrRmqfDvG27o
"""

# Install required libraries

import nltk
nltk.download("vader_lexicon")

import numpy as np
import pandas as pd
import yfinance as yf

from nltk.sentiment.vader import SentimentIntensityAnalyzer

# ==============================
# Market Researcher Agent
# ==============================

sia = SentimentIntensityAnalyzer()


def analyze_news_sentiment(headlines):
    """
    Analyze sentiment from news headlines using VADER.
    Returns average compound sentiment score.
    """
    if not headlines:
        return 0.0

    scores = []
    for h in headlines:
        score = sia.polarity_scores(h)["compound"]
        scores.append(score)

    return float(np.mean(scores))


def analyze_market_regime(df):
    """
    Determine Bullish / Bearish / Sideways regime
    using SMA structure (NO future leakage).
    """
    df = df.copy()

    df["SMA20"] = df["Close"].rolling(20).mean()
    df["SMA50"] = df["Close"].rolling(50).mean()

    df = df.dropna()
    if len(df) < 50:
        return "Unknown", "Not enough historical data"

    last = df.iloc[-1]

    if last["Close"] > last["SMA20"] > last["SMA50"]:
        regime = "Bullish"
    elif last["Close"] < last["SMA20"] < last["SMA50"]:
        regime = "Bearish"
    else:
        regime = "Sideways"

    explanation = (
        f"Close={last['Close']:.2f}, "
        f"SMA20={last['SMA20']:.2f}, "
        f"SMA50={last['SMA50']:.2f}"
    )

    return regime, explanation


def analyze_volatility(df):
    """
    Categorize volatility level based on rolling std.
    """
    returns = df["Close"].pct_change().dropna()
    vol = returns.rolling(20).std().iloc[-1]

    if vol < 0.01:
        return "Low"
    elif vol < 0.02:
        return "Medium"
    else:
        return "High"


def market_research(df, news_headlines):
    """
    Main Market Researcher Agent API
    """
    sentiment = analyze_news_sentiment(news_headlines)
    regime, regime_exp = analyze_market_regime(df)
    volatility = analyze_volatility(df)

    # Simple, explainable confidence heuristic
    confidence = min(
        1.0,
        abs(sentiment) +
        (0.3 if regime != "Sideways" else 0.1)
    )

    explanation = (
        f"Regime: {regime} ({regime_exp}). "
        f"Volatility: {volatility}. "
        f"News sentiment score: {sentiment:.2f}."
    )

    return {
        "regime": regime,
        "volatility": volatility,
        "sentiment_score": round(sentiment, 3),
        "confidence": round(confidence, 2),
        "explanation": explanation
    }

if __name__ == "__main__":
    # Fetch sample stock data
    ticker = "AAPL"
    df = yf.download(ticker, period="6mo", interval="1d")

    # If df has MultiIndex columns, flatten them (assuming the first level contains the desired names)
    # This handles cases like ('Close', 'AAPL'), ('High', 'AAPL') -> 'Close', 'High'
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    # Fake news headlines (replace later with real ones)
    news = [
        "Apple stock rises as company reports strong earnings",
        "Investors optimistic about Apple's AI strategy",
        "Apple faces minor supply chain concerns"
    ]

    output = market_research(df, news)
    print(output)


